#!/usr/bin/env python3

import csv
import xml.etree.ElementTree as ET

tree = ET.parse('seznam.xml')
users = tree.getroot()

# dela csv soubor a zadane nadpisy
csv_file = open('output.csv', 'w')
writer = csv.writer(csv_file)
writer.writerow(['firstname', 'surname', 'age', 'gender'])

# prevod dat z xml do csv
for child in users:
    firstname = child.find('firstname').text
    surname = child.find('surname').text
    age = child.find('age').text
    gender = child.find('gender').text
    writer.writerow([firstname, surname, age, gender])

csv_file.close()
